name: Sync FINAL ALL (NO LFS EVER)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0

      - name: 新建干净分支 + 彻底清空
        run: |
          git config --global user.name "jjjzzz666"
          git config --global user.email "jjjzzz666@users.noreply.github.com"
          git checkout --orphan new_branch
          rm -rf ./*
          rm -f .gitattributes .gitmodules

      # ========== REPO 1 ==========
      - name: Repo1
        run: |
          mkdir -p temp
          curl -L https://github.com/openharmony/applications_app_samples/archive/refs/heads/master.tar.gz | tar xz --strip 1 -C temp
          rm -f temp/.gitattributes temp/.lfsconfig
          find temp -size +10M -delete
          find temp -type d -empty -delete
          mv temp openharmony-applications_app_samples

      # ========== REPO 2 ==========
      - name: Repo2
        run: |
          mkdir -p temp
          curl -L https://github.com/openharmony/docs/archive/refs/heads/master.tar.gz | tar xz --strip 1 -C temp
          rm -f temp/.gitattributes temp/.lfsconfig
          find temp -size +10M -delete
          find temp -type d -empty -delete
          mv temp openharmony-docs

      # ========== REPO 3 ==========
      - name: Repo3
        run: |
          mkdir -p temp
          curl -L https://github.com/openharmony/interface_sdk-js/archive/refs/heads/master.tar.gz | tar xz --strip 1 -C temp
          rm -f temp/.gitattributes temp/.lfsconfig
          find temp -size +10M -delete
          find temp -type d -empty -delete
          mv temp openharmony-interface_sdk-js

      # ========== REPO 4 ==========
      - name: Repo4
        run: |
          git clone https://gitcode.com/HarmonyOS_Samples/guide-snippets.git --depth=1 temp
          rm -rf temp/.git
          rm -f temp/.gitattributes temp/.lfsconfig
          find temp -size +10M -delete
          find temp -type d -empty -delete
          mv temp HarmonyOS_Samples-guide-snippets

      # ========== 强制推送，无任何检查 ==========
      - name: Push FINAL
        run: |
          git add .
          git commit -m "final full sync"
          git branch -M new_branch main
          git push origin main --force --no-verify
